services:
  - type: web
    name: image-to-song-backend
    env: python
    repo: https://github.com/Mokshitha-nelluri/image-to-song.git
    rootDir: backend
    buildCommand: pip install -r requirements-lite.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: SPOTIFY_CLIENT_ID
        value: 25de944a1992453896769027a9ffe3c1
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        value: https://image-to-song-backend.onrender.com/spotify/callback
      - key: RENDER_MEMORY_LIMIT
        value: "true"
